from __future__ import annotations

import hashlib
import io
import json
import subprocess
import sys
import tarfile
from pathlib import Path

import pytest

from scripts.prepare_migration_restore import prepare_restore, render_markdown


STAMP = "20260718T010203Z"
# This is the exact shape generated by release_audit.py when Git identity is
# available.  The fixture exercises it through manifest audit, preparation and
# the planned activation paths rather than accepting it only in a regex test.
RELEASE = "20260718T000000Z-deadbeefcafe"


def _write(path: Path, content: bytes | str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if isinstance(content, bytes):
        path.write_bytes(content)
    else:
        path.write_text(content, encoding="utf-8")


def _plain_fixture(
    tmp_path: Path,
    *,
    tamper: bool = False,
    declared_absent_local_model: bool = False,
    bound_recovery_bundle: bool = False,
    tamper_recovery_bundle_mapping: bool = False,
) -> tuple[Path, str]:
    root = tmp_path / f"finance-radar-migration-{STAMP}"
    release = root / "releases" / RELEASE
    _write(root / "CURRENT_RELEASE.txt", f"/opt/finance-radar/releases/{RELEASE}\n")
    _write(release / "app/api/main.py", "app = 'api'\n")
    _write(release / "app/web/Home.py", "page = 'home'\n")
    _write(release / "app/web/Reviewer.py", "page = 'reviewer'\n")
    _write(release / "app/web/Operator.py", "page = 'operator'\n")
    _write(release / "requirements.txt", "fastapi\n")
    _write(release / "requirements.lock", "fastapi==1.0 --hash=sha256:fixture\n")
    _write(root / "shared/data/finance_radar.sqlite3", b"ledger")
    _write(root / "shared/data/finance_radar_operations.sqlite3", b"operations")
    _write(root / "shared/reports/status.md", "verified\n")
    _write(root / "config/etc/finance-radar.env", "FINANCE_RADAR_DB=/opt/finance-radar/shared/data/finance_radar.sqlite3\n")
    if bound_recovery_bundle:
        snapshot_id = "finance_radar_20260805T000000Z_abcdef12"
        source_entries = []
        mapping = []
        for source_path, target_path in (
            ("ledger.sqlite3", "shared/data/finance_radar.sqlite3"),
            ("operations.sqlite3", "shared/data/finance_radar_operations.sqlite3"),
            ("reports/status.md", "shared/reports/status.md"),
        ):
            payload = root / target_path
            digest = hashlib.sha256(payload.read_bytes()).hexdigest()
            source_entries.append(
                {
                    "path": source_path,
                    "bytes": payload.stat().st_size,
                    "sha256": digest,
                }
            )
            mapping.append(
                {
                    "source_path": source_path,
                    "target_path": target_path,
                    "bytes": payload.stat().st_size,
                    "sha256": digest,
                }
            )
        if tamper_recovery_bundle_mapping:
            mapping[0]["target_path"] = "shared/reports/not-the-ledger.sqlite3"
        source_manifest = {
            "format": "finance-radar-recovery-bundle-v1",
            "snapshot_id": snapshot_id,
            "files": source_entries,
        }
        source_manifest_path = root / "config/MIGRATION_RECOVERY_BUNDLE.manifest.json"
        _write(source_manifest_path, json.dumps(source_manifest, sort_keys=True) + "\n")
        _write(
            root / "config/MIGRATION_RECOVERY_BUNDLE.json",
            json.dumps(
                {
                    "schema_version": 1,
                    "snapshot_id": snapshot_id,
                    "source_manifest_sha256": hashlib.sha256(
                        source_manifest_path.read_bytes()
                    ).hexdigest(),
                    "source_manifest_path": "config/MIGRATION_RECOVERY_BUNDLE.manifest.json",
                    "mapping": mapping,
                    "consistency": "verified_full_recovery_bundle",
                },
                sort_keys=True,
            )
            + "\n",
        )
    if declared_absent_local_model:
        _write(
            release / "deployment/systemd/finance-radar-evidence-llm.service",
            "[Unit]\nDescription=optional local model\n",
        )
        _write(
            root / "config/LOCAL_EVIDENCE_MODEL_CAPABILITY.json",
            json.dumps(
                {
                    "schema_version": 1,
                    "kind": "local_evidence_model",
                    "installed": False,
                    "archive_includes_model": False,
                    "restore_policy": "DISABLED_AFTER_RESTORE",
                }
            ),
        )
    for name in (
        "finance-radar-api.service",
        "finance-radar-web.service",
        "finance-radar-worker.service",
        "finance-radar-backup.service",
        "finance-radar-backup.timer",
    ):
        _write(root / "config/etc/systemd/system" / name, "[Unit]\nDescription=test\n")

    manifest = []
    for path in sorted(item for item in root.rglob("*") if item.is_file()):
        manifest.append(
            f"{hashlib.sha256(path.read_bytes()).hexdigest()}  ./{path.relative_to(root).as_posix()}"
        )
    _write(root / "MANIFEST.sha256", "\n".join(manifest) + "\n")
    if tamper:
        _write(release / "app/api/main.py", "app = 'tampered'\n")

    archive_path = tmp_path / f"finance-radar-migration-{STAMP}.tgz"
    with tarfile.open(archive_path, "w:gz") as archive:
        archive.add(root, arcname=root.name)
        for name in ("data", "reports"):
            member = tarfile.TarInfo(f"{root.name}/releases/{RELEASE}/{name}")
            member.type = tarfile.SYMTYPE
            member.linkname = f"/opt/finance-radar/shared/{name}"
            archive.addfile(member)
    return archive_path, hashlib.sha256(archive_path.read_bytes()).hexdigest()


def _run_activation_metadata_gate(destination: Path) -> subprocess.CompletedProcess[str]:
    source = (
        Path(__file__).resolve().parents[1]
        / "deployment"
        / "systemd"
        / "activate_prepared_restore.sh"
    ).read_text(encoding="utf-8")
    marker = 'python3 - "$PREPARED" "$EXPECTED_RELEASE" <<\'PY\'\n'
    gate = source.split(marker, 1)[1].split("\nPY\n", 1)[0]
    return subprocess.run(
        [sys.executable, "-", str(destination), RELEASE],
        input=gate,
        text=True,
        capture_output=True,
        check=False,
    )


def test_full_archive_is_prepared_without_following_archive_links(tmp_path: Path) -> None:
    archive, digest = _plain_fixture(tmp_path)
    destination = tmp_path / "prepared"
    report = prepare_restore(
        archive,
        destination,
        expected_release=RELEASE,
        expected_sha256=digest,
    )
    assert report["status"] == "PREPARED_NOT_ACTIVATED"
    assert report["manifest_entries_verified"] >= 10
    assert report["symlinks_skipped"] == 2
    assert (destination / "releases" / RELEASE / "app" / "api" / "main.py").is_file()
    assert not (destination / "releases" / RELEASE / "data").exists()
    plan = json.loads((destination / "SYMLINK_PLAN.json").read_text(encoding="utf-8"))
    assert plan == [
        {"path": f"releases/{RELEASE}/data", "target": "/opt/finance-radar/shared/data"},
        {"path": f"releases/{RELEASE}/reports", "target": "/opt/finance-radar/shared/reports"},
    ]
    prepared = json.loads((destination / "PREPARED_RESTORE.json").read_text(encoding="utf-8"))
    assert prepared["boundaries"]["archive_symlinks_followed"] is False
    markdown = render_markdown(prepared)
    assert "Result: **PREPARED_NOT_ACTIVATED**" in markdown
    assert "Trading project included: `False`" in markdown


def test_prepare_refuses_existing_destination_and_manifest_tampering(tmp_path: Path) -> None:
    archive, digest = _plain_fixture(tmp_path)
    existing = tmp_path / "existing"
    existing.mkdir()
    with pytest.raises(FileExistsError, match="already exists"):
        prepare_restore(archive, existing, expected_release=RELEASE, expected_sha256=digest)

    tampered, tampered_digest = _plain_fixture(tmp_path / "tampered", tamper=True)
    with pytest.raises(ValueError, match="manifest verification failed"):
        prepare_restore(
            tampered,
            tmp_path / "tampered-prepared",
            expected_release=RELEASE,
            expected_sha256=tampered_digest,
        )


def test_prepare_preserves_declared_absent_optional_local_model(tmp_path: Path) -> None:
    archive, digest = _plain_fixture(tmp_path, declared_absent_local_model=True)
    destination = tmp_path / "prepared"

    report = prepare_restore(
        archive,
        destination,
        expected_release=RELEASE,
        expected_sha256=digest,
    )

    local_model = report["local_evidence_model"]
    assert local_model["capability_declared"] is True
    assert local_model["included"] is False
    assert local_model["required_by_release"] is False
    assert local_model["restore_policy"] == "DISABLED_AFTER_RESTORE"
    assert (destination / "config/LOCAL_EVIDENCE_MODEL_CAPABILITY.json").is_file()
    assert "Optional local evidence model declared/included: `True` / `False`" in render_markdown(report)


def test_prepare_revalidates_bound_recovery_bundle_before_materializing(tmp_path: Path) -> None:
    archive, digest = _plain_fixture(tmp_path, bound_recovery_bundle=True)
    destination = tmp_path / "prepared"

    report = prepare_restore(
        archive,
        destination,
        expected_release=RELEASE,
        expected_sha256=digest,
    )

    bundle = report["migration_recovery_bundle"]
    assert bundle["bound_to_verified_recovery_bundle"] is True
    assert bundle["legacy_archive_contract"] is False
    assert bundle["consistency"] == "verified_full_recovery_bundle"
    assert bundle["mapped_files"] == 3
    assert (destination / "config/MIGRATION_RECOVERY_BUNDLE.json").is_file()
    assert "Recovery source consistency: `verified_full_recovery_bundle`" in render_markdown(report)


def test_prepare_rejects_tampered_bound_recovery_mapping(tmp_path: Path) -> None:
    archive, digest = _plain_fixture(
        tmp_path,
        bound_recovery_bundle=True,
        tamper_recovery_bundle_mapping=True,
    )

    with pytest.raises(ValueError, match="migration recovery-bundle staged payload"):
        prepare_restore(
            archive,
            tmp_path / "prepared",
            expected_release=RELEASE,
            expected_sha256=digest,
        )


def test_activation_metadata_gate_rejects_bound_marker_report_mismatch(tmp_path: Path) -> None:
    archive, digest = _plain_fixture(tmp_path, bound_recovery_bundle=True)
    destination = tmp_path / "prepared"
    prepare_restore(
        archive,
        destination,
        expected_release=RELEASE,
        expected_sha256=digest,
    )

    assert _run_activation_metadata_gate(destination).returncode == 0

    report_path = destination / "PREPARED_RESTORE.json"
    report = json.loads(report_path.read_text(encoding="utf-8"))
    report["migration_recovery_bundle"] = {
        "bound_to_verified_recovery_bundle": False,
        "legacy_archive_contract": True,
        "consistency": "legacy_unbound_live_copy",
    }
    report_path.write_text(json.dumps(report) + "\n", encoding="utf-8")

    result = _run_activation_metadata_gate(destination)
    assert result.returncode != 0
    assert "prepared recovery-bundle verification is invalid" in result.stderr


def test_activation_metadata_gate_rejects_partial_recovery_markers(tmp_path: Path) -> None:
    archive, digest = _plain_fixture(tmp_path, bound_recovery_bundle=True)
    destination = tmp_path / "prepared"
    prepare_restore(
        archive,
        destination,
        expected_release=RELEASE,
        expected_sha256=digest,
    )
    (destination / "config/MIGRATION_RECOVERY_BUNDLE.json").unlink()

    result = _run_activation_metadata_gate(destination)
    assert result.returncode != 0
    assert "prepared recovery-bundle markers are incomplete" in result.stderr


def test_prepare_rejects_path_traversal_and_forbidden_target(tmp_path: Path) -> None:
    archive = tmp_path / f"finance-radar-migration-{STAMP}.tgz"
    with tarfile.open(archive, "w:gz") as output:
        payload = b"escape"
        member = tarfile.TarInfo(f"finance-radar-migration-{STAMP}/../escape")
        member.size = len(payload)
        output.addfile(member, io.BytesIO(payload))
    digest = hashlib.sha256(archive.read_bytes()).hexdigest()
    with pytest.raises(ValueError, match="unsafe archive member path"):
        prepare_restore(
            archive,
            tmp_path / "unsafe",
            expected_release=RELEASE,
            expected_sha256=digest,
        )

    valid, valid_digest = _plain_fixture(tmp_path / "valid")
    with pytest.raises(ValueError, match="forbidden project"):
        prepare_restore(
            valid,
            tmp_path / "forbidden",
            expected_release=RELEASE,
            expected_sha256=valid_digest,
            target_base="/opt/ethusdc-pivot-bot",
        )


def test_prepare_rejects_unsafe_release_id_before_using_it_as_a_path(tmp_path: Path) -> None:
    archive, digest = _plain_fixture(tmp_path)

    with pytest.raises(ValueError, match="expected release id is invalid"):
        prepare_restore(
            archive,
            tmp_path / "unsafe-release",
            expected_release="20260718T000000Z-deadbeefcafe/../../escape",
            expected_sha256=digest,
        )


def test_activation_script_has_explicit_gates_and_stops_before_nginx() -> None:
    script = (
        Path(__file__).resolve().parents[1]
        / "deployment"
        / "systemd"
        / "activate_prepared_restore.sh"
    ).read_text(encoding="utf-8")
    assert '[ "$CONFIRM" = "--activate" ]' in script
    assert '[ ! -e "$BASE" ]' in script
    assert "refusing to overwrite existing" in script
    assert "PREPARED_RESTORE.json" in script
    assert "prepared recovery-bundle verification is invalid" in script
    assert "prepared recovery-bundle markers are incomplete" in script
    assert "verified_full_recovery_bundle" in script
    assert "^[A-Za-z0-9][A-Za-z0-9._-]{0,95}$" in script
    assert "len(relative.parts) != 3" in script
    assert "systemctl is-active --quiet" in script
    assert "nginx_tls=pending" in script


def test_windows_cutover_orchestrator_defaults_to_audit_only_and_requires_explicit_target() -> None:
    script = (
        Path(__file__).resolve().parents[1] / "scripts" / "restore_migration_to_vps.ps1"
    ).read_text(encoding="utf-8")
    assert "if (-not $Activate)" in script
    assert "AUDIT_ONLY_PASS" in script
    assert "IdentityFile is required for activation" in script
    assert "FINANCE_RADAR_SSH_HOST" in script
    assert "167.172.69.16" not in script
    assert "replacement VPS is not clean" in script
    assert "replacement_vps_preflight.py" in script
    assert "--require-edge-tools" in script
    assert "replacement_vps_preflight_latest.json" in script
    assert "PublicWebUrl must be an HTTPS URL" in script
    assert "^[A-Za-z0-9][A-Za-z0-9._-]{0,95}$" in script
    assert "release_identity.py" in script
    assert "restore release identity dependency transfer failed" in script
    assert "--activate" in script
    assert "PENDING_SEPARATE_CUTOVER" in script
